export interface StoreData {
  store_name_scraped: string;
  start_date: string;
  date: number;
  hour?: number;
  status: string[];
  gross_sales: number;
  orders: number;
  clicks: number;
  impressions: number;
  remaining_budget: number;
  average_daily_budget: number;
  total_spend: number;
  orders_diff: number | null;
  impressions_diff: number | null;
  clicks_diff: number | null;
  gross_sales_diff: number | null;
  remaining_budget_diff: number | null;
  average_daily_budget_diff: number | null;
  total_spend_diff: number;
  CR_GMO: number | null;
  facturacion_gmo: number | null;
  ROAS: number | null;
  CPO: number | null;
  CPC: number | null;
  CPM: number | null;
  pedidos_gmo: number | null;
  daily_budget: number | null;
  impressions_pct_change: number | null;
  clicks_pct_change: number | null;
  orders_pct_change: number | null;
  gross_sales_pct_change: number | null;
  remaining_budget_pct_change: number | null;
  average_daily_budget_pct_change: number | null;
  total_spend_pct_change: number | null;
  CR_GMO_pct_change: number | null;
  facturacion_gmo_pct_change: number | null;
  ROAS_pct_change: number | null;
  CPO_pct_change: number | null;
  CPC_pct_change: number | null;
  CPM_pct_change: number | null;
  pedidos_gmo_pct_change: number | null;
  daily_budget_pct_change: number | null;
}
